version: "2"
run:
  concurrency: 6
linters:
  default: none
  enable:
    - asciicheck
    - bodyclose
    - depguard
    - dogsled
    - durationcheck
    - errcheck
    - errorlint
    - exhaustive
    - forcetypeassert
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - goheader
    - gomodguard
    - goprintffuncname
    - gosec
    - govet
    - importas
    - ineffassign
    - lll
    - makezero
    - misspell
    - nakedret
    - nestif
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - tparallel
    - unconvert
    - unparam
    - unused
    - wastedassign
    - whitespace
  settings:
    depguard:
      rules:
        main:
          allow:
            - $gostd
            - github.com/ComplianceAsCode/ocp4e2e
            - github.com/cenkalti/backoff/v4
            - github.com/ComplianceAsCode/compliance-operator
            - github.com/openshift/machine-config-operator
            - gopkg.in/yaml.v2
            - k8s.io
            - sigs.k8s.io
    errcheck:
      check-type-assertions: true
      check-blank: true
    gocritic:
      enabled-checks:
        - commentedOutCode
        - nilValReturn
        - sloppyReassign
        - weakCond
        - octalLiteral
        - appendCombine
        - equalFold
        - hugeParam
        - indexAlloc
        - rangeExprCopy
        - rangeValCopy
        - boolExprSimplify
        - commentedOutImport
        - docStub
        - emptyFallthrough
        - emptyStringTest
        - hexLiteral
        - methodExprCall
        - stringXbytes
        - typeAssertChain
        - unlabelStmt
        - yodaStyleExpr
        - builtinShadow
        - importShadow
        - initClause
        - nestingReduce
        - paramTypeCombine
        - ptrToRefParam
        - typeUnparen
        - unnamedResult
        - unnecessaryBlock
    godox:
      keywords:
        - BUG
        - FIXME
        - HACK
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/ComplianceAsCode/ocp4e2e)
      custom-order: true
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
